### ISSUE TITLE
What is the license on this code?  WordPress plugin

### ISSUE THREAD

**Issue by moltra** [DantSu/Amazon-Advertising-API#1]
What is the license on this code?  I have been looking for a WordPress plugin to do the same thing that this code does.  Would it be ok to reuse this code in a WordPress plugin.  It would be a private plugin only on my website, at first and then I might share it with the WordPress community.

**Comment by DantSu** [comment]
Hi, I have added a licence to the project. MIT Licence. You can do what you want with this code. Share me the link when you will publish your plug-in, just for curiosity ;)
